#!/usr/bin/env python3
"""
Compare HDF5 snapshot files generated by MAIA solver against legacy golden reference.
Usage:
    python compare_hdf5_snapshots.py --ref <path> --new <path> [--steps 15,51,101]
"""

import argparse
import sys
from pathlib import Path
import h5py
import numpy as np

def load_hdf5_index(filepath: Path):
    index = {}
    with h5py.File(filepath, 'r') as f:
        for gname in f.keys():
            grp = f[gname]
            ts = grp.attrs.get('globalTimeStep', None)
            tp = grp.attrs.get('type', None)
            if ts is not None and tp is not None:
                if isinstance(tp, bytes):
                    tp = tp.decode()
                index[(int(ts), str(tp))] = gname
    return index

def compare_snapshots(ref_path: Path, new_path: Path, steps: list, fields: list = ['U', 'V', 'W']):
    print("=" * 80)
    print("MAIA Solver HDF5 Snapshot Bitwise Verification")
    print(f"Reference HDF5: {ref_path}")
    print(f"Test HDF5     : {new_path}")
    print("=" * 80)

    ref_idx = load_hdf5_index(ref_path)
    new_idx = load_hdf5_index(new_path)

    all_match = True

    with h5py.File(ref_path, 'r') as f_ref, h5py.File(new_path, 'r') as f_new:
        for ts in steps:
            for tp in ['sent', 'received']:
                key = (ts, tp)
                if key not in ref_idx or key not in new_idx:
                    print(f"\nStep {ts:3d} {tp:8s}: Missing in ref or new snapshot")
                    all_match = False
                    continue

                g_ref = f_ref[ref_idx[key]]
                g_new = f_new[new_idx[key]]

                print(f"\n--- Step {ts:3d} ({tp}) ---")
                for field in fields:
                    if field not in g_ref or field not in g_new:
                        print(f"  Field {field}: Missing dataset")
                        all_match = False
                        continue

                    v_ref = np.array(g_ref[field]).astype(np.float64)
                    v_new = np.array(g_new[field]).astype(np.float64)

                    if v_ref.shape != v_new.shape:
                        print(f"  Field {field}: Shape mismatch {v_ref.shape} vs {v_new.shape}")
                        all_match = False
                        continue

                    diff = np.abs(v_ref - v_new)
                    same = np.array_equal(v_ref, v_new)
                    if not same:
                        all_match = False

                    status = "BITWISE IDENTICAL" if same else f"DIFF (max={diff.max():.4e}, nonzeros={np.count_nonzero(diff)})"
                    print(f"  Field {field:2s}: {status}")

    print("\n" + "=" * 80)
    if all_match:
        print("RESULT: ALL REQUESTED SNAPSHOTS ARE BITWISE IDENTICAL (0.000e+00 DIFF)")
    else:
        print("RESULT: SNAPSHOT DIFFERENCES DETECTED")
    print("=" * 80)
    return all_match

def main():
    parser = argparse.ArgumentParser(description="Compare MAIA HDF5 snapshot datasets")
    parser.add_argument("--ref", required=True, type=Path, help="Reference HDF5 snapshot file")
    parser.add_argument("--new", required=True, type=Path, help="New run HDF5 snapshot file")
    parser.add_argument("--steps", default="15,51,101", help="Comma-separated global time steps to compare")
    parser.add_argument("--fields", default="U,V,W", help="Comma-separated fields to compare (default: U,V,W)")
    args = parser.parse_args()

    step_list = [int(s.strip()) for s in args.steps.split(',') if s.strip()]
    field_list = [f.strip() for f in args.fields.split(',') if f.strip()]

    success = compare_snapshots(args.ref, args.new, step_list, field_list)
    if not success:
        sys.exit(1)

if __name__ == "__main__":
    main()
